package com.example.ui.theme

import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF00288E)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFF1E40AF)
val onPrimaryContainerLight = Color(0xFFA8B8FF)
val secondaryLight = Color(0xFF505F76)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFD0E1FB)
val onSecondaryContainerLight = Color(0xFF54647A)
val tertiaryLight = Color(0xFF611E00)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFF872D00)
val onTertiaryContainerLight = Color(0xFFFFA583)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF93000A)
val backgroundLight = Color(0xFFFBF8FF)
val onBackgroundLight = Color(0xFF1A1B22)
val surfaceLight = Color(0xFFFBF8FF)
val onSurfaceLight = Color(0xFF1A1B22)
val surfaceVariantLight = Color(0xFFE3E1EB)
val onSurfaceVariantLight = Color(0xFF444653)
val outlineLight = Color(0xFF757684)
val outlineVariantLight = Color(0xFFC4C5D5)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF2F3037)
val inverseOnSurfaceLight = Color(0xFFF1F0FA)
val inversePrimaryLight = Color(0xFFB8C4FF)
val surfaceDimLight = Color(0xFFDAD9E3)
val surfaceBrightLight = Color(0xFFFBF8FF)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF4F2FC)
val surfaceContainerLight = Color(0xFFEEEDF7)
val surfaceContainerHighLight = Color(0xFFE8E7F1)
val surfaceContainerHighestLight = Color(0xFFE3E1EB)

// Dark Palette
val primaryDark = Color(0xFFB4C5FF)
val onPrimaryDark = Color(0xFF002A78)
val primaryContainerDark = Color(0xFF1E40AF)
val onPrimaryContainerDark = Color(0xFFDBE1FF)
val secondaryDark = Color(0xFFB8C8E1)
val onSecondaryDark = Color(0xFF223246)
val secondaryContainerDark = Color(0xFF39485D)
val onSecondaryContainerDark = Color(0xFFD4E4FD)
val tertiaryDark = Color(0xFFFFB59C)
val onTertiaryDark = Color(0xFF5B1A00)
val tertiaryContainerDark = Color(0xFF802700)
val onTertiaryContainerDark = Color(0xFFFFDBCF)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF111318)
val onBackgroundDark = Color(0xFFE2E2E9)
val surfaceDark = Color(0xFF111318)
val onSurfaceDark = Color(0xFFE2E2E9)
val surfaceVariantDark = Color(0xFF44474F)
val onSurfaceVariantDark = Color(0xFFC4C6D0)
val outlineDark = Color(0xFF8E9099)
val outlineVariantDark = Color(0xFF44474F)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFE2E2E9)
val inverseOnSurfaceDark = Color(0xFF2E3036)
val inversePrimaryDark = Color(0xFF2B57B0)
val surfaceDimDark = Color(0xFF111318)
val surfaceBrightDark = Color(0xFF37393E)
val surfaceContainerLowestDark = Color(0xFF0C0E13)
val surfaceContainerLowDark = Color(0xFF191B20)
val surfaceContainerDark = Color(0xFF1D2024)
val surfaceContainerHighDark = Color(0xFF282A2F)
val surfaceContainerHighestDark = Color(0xFF33353A)

